name             'rolling_deploy'
maintainer       'Stathy, Inc.'
maintainer_email 'stathy@stathy.com'
license          'Apache 2.0'
description      'Rolling deployment resources for system and application configuration change.'
long_description 'Description\n===========\n\nThis cookbook is used to create a rolling deployment of change within an environment by containing sections of the environment called legs and chaining the deployment between legs and the nodes within each leg. The concept is to reduce risk of change by trickling change into an environment and accelerating release based on success of previous 'legs'. For example: 1 -> [2,3,4] -> [5,6,7,8,9,10,11,12] -> [13 .. rest]'
version          '0.0.5'
